//file:noinspection DependencyNotationArgument
// TODO remove when fixed in RFG ^
/*
 * Add your dependencies here. Common configurations:
 *  - implementation("group:name:version:classifier"): if you need this for internal implementation details of the mod.
 *       Available at compiletime and runtime for your environment.
 *
 *  - compileOnlyApi("g:n:v:c"): if you need this for internal implementation details of the mod.
 *       Available at compiletime but not runtime for your environment.
 *
 *  - annotationProcessor("g:n:v:c"): mostly for java compiler plugins, if you know you need this, use it, otherwise don't worry
 *
 *  - testCONFIG("g:n:v:c"): replace CONFIG by one of the above, same as above but for the test sources instead of main
 *
 * You can exclude transitive dependencies (dependencies of the chosen dependency) by appending { transitive = false } if needed.
 *
 * To add a mod with CurseMaven, replace '("g:n:v:c")' in the above with 'rfg.deobf("curse.maven:project_slug-project_id:file_id")'
 * Example: implementation rfg.deobf("curse.maven:gregtech-ce-unofficial-557242:4527757")
 *
 * To shadow a dependency, use 'shadowImplementation'. For more info, see https://github.com/GregTechCEu/Buildscripts/blob/master/docs/shadow.md
 *
 * For more details, see https://docs.gradle.org/8.0.1/userguide/java_library_plugin.html#sec:java_library_configurations_graph
 */
repositories {
    // Other repositories described by default:
    // CleanroomMC: https://maven.cleanroommc.com
    flatDir {
        dirs 'libs'
    }
    exclusiveContent {
        forRepository {
            maven {
                name 'CurseMaven'
                url 'https://cursemaven.com'
            }
        }
        filter {
            includeGroup 'curse.maven'
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                name 'Modrinth'
                url 'https://api.modrinth.com/maven'
            }
        }
        filter {
            includeGroup 'maven.modrinth'
        }
    }
    mavenLocal() // Must be last for caching to work
}

dependencies {

    // Hard Dependencies
    api(rfg.deobf(project.files("lib/gregtech-1.12.2-2.9.0-beta-dev.jar"))) // GTCEu 2.9.0
    api(rfg.deobf(project.files("lib/supercritical-0.2.6-dev.jar")))
    api(rfg.deobf(project.files("lib/CodeChickenLib-1.12.2-3.2.3.358-universal.jar"))) // CCL 3.2.3.358
    api(rfg.deobf(project.files("lib/gcym-1.12.2-1.2.11-dev.jar"))) //GCYM 1.3
    implementation("com.cleanroommc:groovyscript:1.4.3") { transitive = false }
    api(rfg.deobf(project.files("lib/MaterialReplication-1.2.7-dev.jar"))) //Material replication 1.3.0
    api("curse.maven:had-enough-items-557549:5906628")
    api("org.jetbrains:annotations:26.1.0")

    // Soft Dependencies
    api("curse.maven:crafttweaker-239197:5486112")
    api(rfg.deobf("curse.maven:ctm-267602:2915363")) // CTM 1.0.2.31
    api(rfg.deobf("curse.maven:ae2-extended-life-570458:5147702")) // AE2UEL 0.56.4
    api(rfg.deobf("curse.maven:ae2-fluid-crafting-rework-623955:5751930"))
    api(rfg.deobf("curse.maven:galacticraft-legacy-564236:4671122"))
    api("com.cleanroommc:modularui:3.1.6") { transitive = false }

    compileOnly("curse.maven:journeymap-32274:5172461") // Journeymap 5.7.1p3
    compileOnly("curse.maven:voxelmap-225179:3029445") // VoxelMap 1.9.28
    compileOnly("curse.maven:xaeros-263420:5394758") // Xaero's Minimap 24.2.0

}
